Traceback (most recent call last):
  File "/home/codespace/.cache/pypoetry/virtualenvs/python-book-eng-Xz8nEEY6-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.cache/pypoetry/virtualenvs/python-book-eng-Xz8nEEY6-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/codespace/.cache/pypoetry/virtualenvs/python-book-eng-Xz8nEEY6-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/local/python/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/codespace/.cache/pypoetry/virtualenvs/python-book-eng-Xz8nEEY6-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.cache/pypoetry/virtualenvs/python-book-eng-Xz8nEEY6-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.cache/pypoetry/virtualenvs/python-book-eng-Xz8nEEY6-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt

def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

# Generate the first 10 Fibonacci numbers
fib_sequence = [fibonacci(i) for i in range(10)]

# Plot the Fibonacci sequence
plt.figure(figsize=(10, 6))
plt.plot(range(10), fib_sequence, marker='o', linestyle='-', color='b')
plt.title('Fibonacci Sequence')
plt.xlabel('n')
plt.ylabel('Fibonacci Number')
plt.grid(True)
plt.show()

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      3[0m [38;5;28;01mdef[39;00m [38;5;21mfibonacci[39m(n):
[1;32m      4[0m     [38;5;28;01mif[39;00m n [38;5;241m==[39m [38;5;241m0[39m:

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'

